# Tuning de Hiperparâmetros — XGBoost

Notebook para explorar combinações de hiperparâmetros do XGBClassifier.

**Fluxo:**
1. Carrega dados processados
2. Divide em treino / validação / teste (estratificado)
3. Testa combinações via `ParameterGrid` na validação (F1 Score)
4. Retreina com melhores params no treino completo
5. Avalia no teste holdout

Ajuste o `PARAM_GRID` e reexecute as cells a partir da cell 4 a cada iteração.

In [1]:
import sys
sys.path.insert(0, "..")

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    f1_score,
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    confusion_matrix,
    matthews_corrcoef,
)
from sklearn.model_selection import train_test_split, ParameterGrid
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder
from xgboost import XGBClassifier

from config import (
    PROCESSED_TRAIN_FILE,
    TARGET_COL,
    NUMERIC_FEATURES,
    CATEGORICAL_FEATURES,
)

print("Imports OK")

Imports OK

## 1. Carregar dados e dividir em treino / validação / teste

In [2]:
# =============================================
# HIPERPARÂMETROS DE SPLIT — ajuste se quiser
# =============================================
RANDOM_STATE = 42
TEST_SIZE = 0.20
VALIDATION_SIZE = 0.10

# Carregar dados processados
df = pd.read_csv(PROCESSED_TRAIN_FILE)
print(f"Dataset: {df.shape[0]:,} linhas × {df.shape[1]} colunas")
print(f"Distribuição do target:")
print(df[TARGET_COL].value_counts().rename({1: "Admissão (1)", -1: "Desligamento (-1)"}))

# Separar features e target
feature_cols = list(NUMERIC_FEATURES) + list(CATEGORICAL_FEATURES)
X = df[feature_cols].copy()
y = df[TARGET_COL].map({1: 1, -1: 0})  # XGBoost espera labels >= 0

# Split 1: treino_completo (80%) + teste (20%)
X_train_full, X_test, y_train_full, y_test = train_test_split(
    X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
)

# Split 2: treino (90% do treino_completo) + validação (10%)
X_train, X_val, y_train, y_val = train_test_split(
    X_train_full, y_train_full,
    test_size=VALIDATION_SIZE, random_state=RANDOM_STATE, stratify=y_train_full
)

print(f"\nTamanhos:")
print(f"  Treino       : {X_train.shape[0]:>10,}")
print(f"  Validação    : {X_val.shape[0]:>10,}")
print(f"  Treino compl.: {X_train_full.shape[0]:>10,}")
print(f"  Teste        : {X_test.shape[0]:>10,}")

Dataset: 738,837 linhas × 21 colunas
Distribuição do target:
saldomovimentacao
Desligamento (-1)    377254
Admissão (1)         361583
Name: count, dtype: int64

Tamanhos:
  Treino       :    531,962
  Validação    :     59,107
  Treino compl.:    591,069
  Teste        :    147,768

In [3]:
resumo = df.nunique().to_frame("n_unicos")
resumo["tipo"] = df.dtypes

display(resumo.sort_values(by="n_unicos", ascending=False))

                     n_unicos     tipo
salario                 60305  float64
cbo2002ocupacao          1841    int64
horascontratuais         1099  float64
subclasse                1035    int64
idade                      76  float64
secao                      21      str
municipio                  16    int64
graudeinstrucao            13    int64
tamestabjan                10    int64
racacor                     7    int64
tipodedeficiencia           7    int64
categoria                   7    int64
tipoestabelecimento         3    int64
indtrabparcial              3    int64
tipoempregador              3    int64
sexo                        3    int64
indtrabintermitente         3    int64
mes                         3    int64
saldomovimentacao           2    int64
indicadoraprendiz           2    int64
ano                         2    int64

## 2. Preprocessador

In [4]:
numeric_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
])

categorical_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="constant", fill_value="desconhecido")),
    ("encoder", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)),
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_pipeline, list(NUMERIC_FEATURES)),
        ("cat", categorical_pipeline, list(CATEGORICAL_FEATURES)),
    ],
    remainder="drop",
)

print("Preprocessador montado.")

Preprocessador montado.

## 3. Função de Grid Search

Função reutilizável que recebe um `param_grid`, executa o grid search na validação e exibe o ranking.
Chame quantas vezes quiser com parâmetros diferentes — cada execução fica registrada como justificativa.

In [5]:
def run_grid_search(param_grid: dict) -> tuple[dict, float, pd.DataFrame]:
    """
    Executa grid search manual na validação e exibe o ranking dos resultados.

    Parameters:
        param_grid: Dicionário com hiperparâmetros a testar (formato ParameterGrid).

    Returns:
        Tupla (melhores_params, melhor_f1, dataframe_ranking).
    """
    grid = list(ParameterGrid(param_grid))
    total = len(grid)
    print(f"Total de combinações a testar: {total}")
    print("=" * 80)

    results = []
    best_score = -np.inf
    best_params = None

    for i, params in enumerate(grid, 1):
        clf = XGBClassifier(
            **params,
            objective="binary:logistic",
            eval_metric="logloss",
            n_jobs=-1,
            random_state=RANDOM_STATE,
        )

        pipe = Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("classifier", clf),
        ])

        pipe.fit(X_train, y_train)
        y_val_pred = pipe.predict(X_val)
        score = f1_score(y_val, y_val_pred)

        marker = " *** NOVO MELHOR" if score > best_score else ""
        print(f"[{i:>{len(str(total))}}/{total}] F1: {score:.4f}{marker} | {params}")

        results.append({"f1_val": score, **params})

        if score > best_score:
            best_score = score
            best_params = params

    print("=" * 80)
    print(f"\nMelhores hiperparâmetros: {best_params}")
    print(f"Melhor F1 (validação): {best_score:.4f}")

    # Ranking
    df_results = pd.DataFrame(results).sort_values("f1_val", ascending=False).reset_index(drop=True)
    df_results.index += 1
    df_results.index.name = "rank"
    display(df_results)

    return best_params, best_score, df_results

print("Função run_grid_search() definida.")

Função run_grid_search() definida.

## 4. Execuções do Grid Search

Cada cell abaixo é uma execução com parâmetros diferentes.
Duplique a cell, ajuste o grid e execute novamente — o histórico fica registrado.

### Execução 1 — Exploração inicial ampla

Grade ampla para identificar regiões promissoras do espaço de hiperparâmetros. Sem conclusões prévias para guiar os parâmetros escolhidos.

In [ ]:
best_params, best_score, df_results = run_grid_search({
    "n_estimators": [300, 500],
    "max_depth": [4, 6, 8],
    "learning_rate": [0.05, 0.1],
    "min_child_weight": [1, 5],
    "subsample": [0.8],
    "colsample_bytree": [0.8],
})

Total de combinações a testar: 24
================================================================================
[ 1/24] F1: 0.5883 *** NOVO MELHOR | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
[ 2/24] F1: 0.5921 *** NOVO MELHOR | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.8}
[ 3/24] F1: 0.5894 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 5, 'n_estimators': 300, 'subsample': 0.8}
[ 4/24] F1: 0.5913 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[ 5/24] F1: 0.6022 *** NOVO MELHOR | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 6, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
[ 6/24] F1: 0.6088 *** NOVO MELHOR | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 6, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.8}
[ 7/24] F1: 0.6012 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 6, 'min_child_weight': 5, 'n_estimators': 300, 'subsample': 0.8}
[ 8/24] F1: 0.6089 *** NOVO MELHOR | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 6, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[ 9/24] F1: 0.6131 *** NOVO MELHOR | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
[10/24] F1: 0.6202 *** NOVO MELHOR | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.8}
[11/24] F1: 0.6127 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 300, 'subsample': 0.8}
[12/24] F1: 0.6197 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[13/24] F1: 0.5915 | {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
[14/24] F1: 0.5992 | {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 4, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.8}
[15/24] F1: 0.5907 | {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 4, 'min_child_weight': 5, 'n_estimators': 300, 'subsample': 0.8}
[16/24] F1: 0.5981 | {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 4, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[17/24] F1: 0.6089 | {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 6, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
[18/24] F1: 0.6143 | {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 6, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.8}
[19/24] F1: 0.6084 | {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 6, 'min_child_weight': 5, 'n_estimators': 300, 'subsample': 0.8}
[20/24] F1: 0.6132 | {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 6, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[21/24] F1: 0.6196 | {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 300, 'subsample': 0.8}
[22/24] F1: 0.6204 *** NOVO MELHOR | {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.8}
[23/24] F1: 0.6183 | {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 300, 'subsample': 0.8}
[24/24] F1: 0.6209 *** NOVO MELHOR | {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
================================================================================

Melhores hiperparâmetros: {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
Melhor F1 (validação): 0.6209

,f1_val,colsample_bytree,learning_rate,max_depth,min_child_weight,n_estimators,subsample
rank,,,,,,,
1,0.620868,0.8,0.10,8,5,500,0.8
2,0.620411,0.8,0.10,8,1,500,0.8
3,0.620229,0.8,0.05,8,1,500,0.8
4,0.619653,0.8,0.05,8,5,500,0.8
5,0.619589,0.8,0.10,8,1,300,0.8
6,0.618264,0.8,0.10,8,5,300,0.8
7,0.614316,0.8,0.10,6,1,500,0.8
8,0.613233,0.8,0.10,6,5,500,0.8
9,0.613087,0.8,0.05,8,1,300,0.8
10,0.612715,0.8,0.05,8,5,300,0.8
11,0.608939,0.8,0.05,6,5,500,0.8
12,0.608880,0.8,0.10,6,1,300,0.8
13,0.608822,0.8,0.05,6,1,500,0.8
14,0.608364,0.8,0.10,6,5,300,0.8
15,0.602243,0.8,0.05,6,1,300,0.8
16,0.601204,0.8,0.05,6,5,300,0.8
17,0.599226,0.8,0.10,4,1,500,0.8
18,0.598122,0.8,0.10,4,5,500,0.8
19,0.592148,0.8,0.05,4,1,500,0.8
20,0.591492,0.8,0.10,4,1,300,0.8
21,0.591349,0.8,0.05,4,5,500,0.8
22,0.590682,0.8,0.10,4,5,300,0.8
23,0.589420,0.8,0.05,4,5,300,0.8
24,0.588329,0.8,0.05,4,1,300,0.8

### Execução 2 — Expansão em profundidade e estimadores

A execução 1 indicou que `max_depth` mais profundo e `n_estimators` maiores consistentemente melhoravam o F1, com ambos na borda superior da grade — sinal de que havia espaço para explorar além. Expandiu-se também `subsample` e `colsample_bytree`. Os resultados mostraram que `max_depth=12` com `learning_rate=0.1` causa overfitting claro (F1 cai com mais estimadores), enquanto `learning_rate=0.05` se mostrou mais estável em profundidades maiores. `colsample_bytree=0.7` apresentou leve vantagem sobre `0.8`.

In [ ]:
best_params, best_score, df_results = run_grid_search({
    "n_estimators": [500, 700, 1000],
    "max_depth": [8, 10, 12],
    "learning_rate": [0.05, 0.1],
    "min_child_weight": [1, 3, 5],
    "subsample": [0.7, 0.8],
    "colsample_bytree": [0.7, 0.8],
})

Total de combinações a testar: 216
================================================================================
[  1/216] F1: 0.6185 *** NOVO MELHOR | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.7}
[  2/216] F1: 0.6189 *** NOVO MELHOR | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.8}
[  3/216] F1: 0.6200 *** NOVO MELHOR | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.7}
[  4/216] F1: 0.6215 *** NOVO MELHOR | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.8}
[  5/216] F1: 0.6211 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 1000, 'subsample': 0.7}
[  6/216] F1: 0.6243 *** NOVO MELHOR | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 1000, 'subsample': 0.8}
[  7/216] F1: 0.6200 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 500, 'subsample': 0.7}
[  8/216] F1: 0.6186 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 500, 'subsample': 0.8}
[  9/216] F1: 0.6225 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 700, 'subsample': 0.7}
[ 10/216] F1: 0.6206 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 700, 'subsample': 0.8}
[ 11/216] F1: 0.6230 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 1000, 'subsample': 0.7}
[ 12/216] F1: 0.6241 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 1000, 'subsample': 0.8}
[ 13/216] F1: 0.6187 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.7}
[ 14/216] F1: 0.6187 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[ 15/216] F1: 0.6213 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.7}
[ 16/216] F1: 0.6209 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.8}
[ 17/216] F1: 0.6220 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.7}
[ 18/216] F1: 0.6231 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.8}
[ 19/216] F1: 0.6258 *** NOVO MELHOR | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.7}
[ 20/216] F1: 0.6244 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.8}
[ 21/216] F1: 0.6240 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.7}
[ 22/216] F1: 0.6220 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.8}
[ 23/216] F1: 0.6214 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 1000, 'subsample': 0.7}
[ 24/216] F1: 0.6209 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 1000, 'subsample': 0.8}
[ 25/216] F1: 0.6233 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 3, 'n_estimators': 500, 'subsample': 0.7}
[ 26/216] F1: 0.6256 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 3, 'n_estimators': 500, 'subsample': 0.8}
[ 27/216] F1: 0.6228 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 3, 'n_estimators': 700, 'subsample': 0.7}
[ 28/216] F1: 0.6256 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 3, 'n_estimators': 700, 'subsample': 0.8}
[ 29/216] F1: 0.6223 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 3, 'n_estimators': 1000, 'subsample': 0.7}
[ 30/216] F1: 0.6236 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 3, 'n_estimators': 1000, 'subsample': 0.8}
[ 31/216] F1: 0.6236 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.7}
[ 32/216] F1: 0.6239 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[ 33/216] F1: 0.6235 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.7}
[ 34/216] F1: 0.6240 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.8}
[ 35/216] F1: 0.6217 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.7}
[ 36/216] F1: 0.6232 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.8}
[ 37/216] F1: 0.6233 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.7}
[ 38/216] F1: 0.6242 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.8}
[ 39/216] F1: 0.6197 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.7}
[ 40/216] F1: 0.6215 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.8}
[ 41/216] F1: 0.6162 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 1, 'n_estimators': 1000, 'subsample': 0.7}
[ 42/216] F1: 0.6169 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 1, 'n_estimators': 1000, 'subsample': 0.8}
[ 43/216] F1: 0.6239 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 3, 'n_estimators': 500, 'subsample': 0.7}
[ 44/216] F1: 0.6241 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 3, 'n_estimators': 500, 'subsample': 0.8}
[ 45/216] F1: 0.6219 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 3, 'n_estimators': 700, 'subsample': 0.7}
[ 46/216] F1: 0.6220 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 3, 'n_estimators': 700, 'subsample': 0.8}
[ 47/216] F1: 0.6180 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 3, 'n_estimators': 1000, 'subsample': 0.7}
[ 48/216] F1: 0.6171 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 3, 'n_estimators': 1000, 'subsample': 0.8}
[ 49/216] F1: 0.6227 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.7}
[ 50/216] F1: 0.6263 *** NOVO MELHOR | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[ 51/216] F1: 0.6222 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.7}
[ 52/216] F1: 0.6249 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.8}
[ 53/216] F1: 0.6185 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.7}
[ 54/216] F1: 0.6198 | {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.8}
[ 55/216] F1: 0.6214 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.7}
[ 56/216] F1: 0.6234 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.8}
[ 57/216] F1: 0.6187 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.7}
[ 58/216] F1: 0.6231 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.8}
[ 59/216] F1: 0.6187 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 1000, 'subsample': 0.7}
[ 60/216] F1: 0.6215 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 1000, 'subsample': 0.8}
[ 61/216] F1: 0.6209 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 500, 'subsample': 0.7}
[ 62/216] F1: 0.6220 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 500, 'subsample': 0.8}
[ 63/216] F1: 0.6197 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 700, 'subsample': 0.7}
[ 64/216] F1: 0.6226 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 700, 'subsample': 0.8}
[ 65/216] F1: 0.6198 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 1000, 'subsample': 0.7}
[ 66/216] F1: 0.6224 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 1000, 'subsample': 0.8}
[ 67/216] F1: 0.6210 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.7}
[ 68/216] F1: 0.6233 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[ 69/216] F1: 0.6210 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.7}
[ 70/216] F1: 0.6232 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.8}
[ 71/216] F1: 0.6196 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.7}
[ 72/216] F1: 0.6220 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.8}
[ 73/216] F1: 0.6204 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.7}
[ 74/216] F1: 0.6206 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.8}
[ 75/216] F1: 0.6188 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.7}
[ 76/216] F1: 0.6179 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.8}
[ 77/216] F1: 0.6160 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 1000, 'subsample': 0.7}
[ 78/216] F1: 0.6143 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 1000, 'subsample': 0.8}
[ 79/216] F1: 0.6215 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 3, 'n_estimators': 500, 'subsample': 0.7}
[ 80/216] F1: 0.6209 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 3, 'n_estimators': 500, 'subsample': 0.8}
[ 81/216] F1: 0.6188 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 3, 'n_estimators': 700, 'subsample': 0.7}
[ 82/216] F1: 0.6194 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 3, 'n_estimators': 700, 'subsample': 0.8}
[ 83/216] F1: 0.6161 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 3, 'n_estimators': 1000, 'subsample': 0.7}
[ 84/216] F1: 0.6168 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 3, 'n_estimators': 1000, 'subsample': 0.8}
[ 85/216] F1: 0.6217 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.7}
[ 86/216] F1: 0.6238 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[ 87/216] F1: 0.6197 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.7}
[ 88/216] F1: 0.6208 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.8}
[ 89/216] F1: 0.6166 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.7}
[ 90/216] F1: 0.6181 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.8}
[ 91/216] F1: 0.6141 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.7}
[ 92/216] F1: 0.6137 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.8}
[ 93/216] F1: 0.6091 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.7}
[ 94/216] F1: 0.6094 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.8}
[ 95/216] F1: 0.6032 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 1, 'n_estimators': 1000, 'subsample': 0.7}
[ 96/216] F1: 0.6026 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 1, 'n_estimators': 1000, 'subsample': 0.8}
[ 97/216] F1: 0.6172 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 3, 'n_estimators': 500, 'subsample': 0.7}
[ 98/216] F1: 0.6174 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 3, 'n_estimators': 500, 'subsample': 0.8}
[ 99/216] F1: 0.6123 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 3, 'n_estimators': 700, 'subsample': 0.7}
[100/216] F1: 0.6143 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 3, 'n_estimators': 700, 'subsample': 0.8}
[101/216] F1: 0.6070 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 3, 'n_estimators': 1000, 'subsample': 0.7}
[102/216] F1: 0.6090 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 3, 'n_estimators': 1000, 'subsample': 0.8}
[103/216] F1: 0.6178 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.7}
[104/216] F1: 0.6174 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[105/216] F1: 0.6147 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.7}
[106/216] F1: 0.6147 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.8}
[107/216] F1: 0.6093 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.7}
[108/216] F1: 0.6093 | {'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.8}
[109/216] F1: 0.6192 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.7}
[110/216] F1: 0.6197 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.8}
[111/216] F1: 0.6201 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.7}
[112/216] F1: 0.6210 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.8}
[113/216] F1: 0.6229 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 1000, 'subsample': 0.7}
[114/216] F1: 0.6227 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 1, 'n_estimators': 1000, 'subsample': 0.8}
[115/216] F1: 0.6180 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 500, 'subsample': 0.7}
[116/216] F1: 0.6188 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 500, 'subsample': 0.8}
[117/216] F1: 0.6191 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 700, 'subsample': 0.7}
[118/216] F1: 0.6207 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 700, 'subsample': 0.8}
[119/216] F1: 0.6223 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 1000, 'subsample': 0.7}
[120/216] F1: 0.6216 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 3, 'n_estimators': 1000, 'subsample': 0.8}
[121/216] F1: 0.6184 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.7}
[122/216] F1: 0.6193 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[123/216] F1: 0.6196 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.7}
[124/216] F1: 0.6209 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.8}
[125/216] F1: 0.6213 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.7}
[126/216] F1: 0.6222 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.8}
[127/216] F1: 0.6231 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.7}
[128/216] F1: 0.6242 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 500, 'subsample': 0.8}
[129/216] F1: 0.6213 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.7}
[130/216] F1: 0.6248 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 700, 'subsample': 0.8}
[131/216] F1: 0.6209 | {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 1, 'n_estimators': 1000, 'subsample': 0.7}

,f1_val,colsample_bytree,learning_rate,max_depth,min_child_weight,n_estimators,subsample
rank,,,,,,,
1,0.626329,0.7,0.05,12,5,500,0.8
2,0.625824,0.7,0.05,10,1,500,0.7
3,0.625625,0.7,0.05,10,3,500,0.8
4,0.625574,0.7,0.05,10,3,700,0.8
5,0.625215,0.8,0.05,10,5,700,0.7
...,...,...,...,...,...,...,...
212,0.604342,0.8,0.10,12,3,1000,0.7
213,0.603215,0.7,0.10,12,1,1000,0.7
214,0.602577,0.7,0.10,12,1,1000,0.8
215,0.602485,0.8,0.10,12,1,1000,0.7
216,0.602362,0.8,0.10,12,1,1000,0.8

### Execução 3 — Refinamento: learning rate menor e colsample reduzido

A execução 2 sugeriu que menor `colsample_bytree` e menor `learning_rate` favoreciam a generalização em profundidades maiores. Introduziu-se `learning_rate=0.03` e `colsample_bytree=0.6`, que dominaram o topo do ranking, confirmando a hipótese.

In [ ]:
best_params, best_score, df_results = run_grid_search({
    "n_estimators": [400, 500, 600],
    "max_depth": [10, 11, 12],
    "learning_rate": [0.03, 0.05],
    "min_child_weight": [5, 7, 10],
    "subsample": [0.8, 0.9],
    "colsample_bytree": [0.6, 0.7],
})

Total de combinações a testar: 216
================================================================================
[  1/216] F1: 0.6217 *** NOVO MELHOR | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.8}
[  2/216] F1: 0.6216 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.9}
[  3/216] F1: 0.6230 *** NOVO MELHOR | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[  4/216] F1: 0.6236 *** NOVO MELHOR | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.9}
[  5/216] F1: 0.6240 *** NOVO MELHOR | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.8}
[  6/216] F1: 0.6250 *** NOVO MELHOR | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.9}
[  7/216] F1: 0.6207 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 400, 'subsample': 0.8}
[  8/216] F1: 0.6205 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 400, 'subsample': 0.9}
[  9/216] F1: 0.6228 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 500, 'subsample': 0.8}
[ 10/216] F1: 0.6235 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 500, 'subsample': 0.9}
[ 11/216] F1: 0.6239 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.8}
[ 12/216] F1: 0.6244 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.9}
[ 13/216] F1: 0.6216 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 400, 'subsample': 0.8}
[ 14/216] F1: 0.6203 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 400, 'subsample': 0.9}
[ 15/216] F1: 0.6237 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 500, 'subsample': 0.8}
[ 16/216] F1: 0.6226 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 500, 'subsample': 0.9}
[ 17/216] F1: 0.6242 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 600, 'subsample': 0.8}
[ 18/216] F1: 0.6248 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 600, 'subsample': 0.9}
[ 19/216] F1: 0.6235 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.8}
[ 20/216] F1: 0.6240 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.9}
[ 21/216] F1: 0.6257 *** NOVO MELHOR | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[ 22/216] F1: 0.6260 *** NOVO MELHOR | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.9}
[ 23/216] F1: 0.6256 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.8}
[ 24/216] F1: 0.6271 *** NOVO MELHOR | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.9}
[ 25/216] F1: 0.6233 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 7, 'n_estimators': 400, 'subsample': 0.8}
[ 26/216] F1: 0.6242 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 7, 'n_estimators': 400, 'subsample': 0.9}
[ 27/216] F1: 0.6253 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 7, 'n_estimators': 500, 'subsample': 0.8}
[ 28/216] F1: 0.6254 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 7, 'n_estimators': 500, 'subsample': 0.9}
[ 29/216] F1: 0.6264 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.8}
[ 30/216] F1: 0.6264 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.9}
[ 31/216] F1: 0.6225 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 10, 'n_estimators': 400, 'subsample': 0.8}
[ 32/216] F1: 0.6225 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 10, 'n_estimators': 400, 'subsample': 0.9}
[ 33/216] F1: 0.6244 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 10, 'n_estimators': 500, 'subsample': 0.8}
[ 34/216] F1: 0.6255 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 10, 'n_estimators': 500, 'subsample': 0.9}
[ 35/216] F1: 0.6254 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 10, 'n_estimators': 600, 'subsample': 0.8}
[ 36/216] F1: 0.6261 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 10, 'n_estimators': 600, 'subsample': 0.9}
[ 37/216] F1: 0.6259 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.8}
[ 38/216] F1: 0.6264 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.9}
[ 39/216] F1: 0.6276 *** NOVO MELHOR | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[ 40/216] F1: 0.6267 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.9}
[ 41/216] F1: 0.6285 *** NOVO MELHOR | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.8}
[ 42/216] F1: 0.6268 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.9}
[ 43/216] F1: 0.6252 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 400, 'subsample': 0.8}
[ 44/216] F1: 0.6267 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 400, 'subsample': 0.9}
[ 45/216] F1: 0.6259 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 500, 'subsample': 0.8}
[ 46/216] F1: 0.6277 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 500, 'subsample': 0.9}
[ 47/216] F1: 0.6265 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.8}
[ 48/216] F1: 0.6275 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.9}
[ 49/216] F1: 0.6253 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 10, 'n_estimators': 400, 'subsample': 0.8}
[ 50/216] F1: 0.6255 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 10, 'n_estimators': 400, 'subsample': 0.9}
[ 51/216] F1: 0.6258 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 10, 'n_estimators': 500, 'subsample': 0.8}
[ 52/216] F1: 0.6274 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 10, 'n_estimators': 500, 'subsample': 0.9}
[ 53/216] F1: 0.6264 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 10, 'n_estimators': 600, 'subsample': 0.8}
[ 54/216] F1: 0.6277 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 10, 'n_estimators': 600, 'subsample': 0.9}
[ 55/216] F1: 0.6224 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.8}
[ 56/216] F1: 0.6233 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.9}
[ 57/216] F1: 0.6240 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[ 58/216] F1: 0.6250 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.9}
[ 59/216] F1: 0.6239 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.8}
[ 60/216] F1: 0.6260 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.9}
[ 61/216] F1: 0.6246 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 400, 'subsample': 0.8}
[ 62/216] F1: 0.6229 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 400, 'subsample': 0.9}
[ 63/216] F1: 0.6243 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 500, 'subsample': 0.8}
[ 64/216] F1: 0.6246 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 500, 'subsample': 0.9}
[ 65/216] F1: 0.6248 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.8}
[ 66/216] F1: 0.6247 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.9}
[ 67/216] F1: 0.6213 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 400, 'subsample': 0.8}
[ 68/216] F1: 0.6231 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 400, 'subsample': 0.9}
[ 69/216] F1: 0.6235 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 500, 'subsample': 0.8}
[ 70/216] F1: 0.6251 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 500, 'subsample': 0.9}
[ 71/216] F1: 0.6237 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 600, 'subsample': 0.8}
[ 72/216] F1: 0.6244 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 600, 'subsample': 0.9}
[ 73/216] F1: 0.6259 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.8}
[ 74/216] F1: 0.6250 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.9}
[ 75/216] F1: 0.6250 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[ 76/216] F1: 0.6260 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.9}
[ 77/216] F1: 0.6253 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.8}
[ 78/216] F1: 0.6254 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.9}
[ 79/216] F1: 0.6247 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 7, 'n_estimators': 400, 'subsample': 0.8}
[ 80/216] F1: 0.6239 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 7, 'n_estimators': 400, 'subsample': 0.9}
[ 81/216] F1: 0.6244 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 7, 'n_estimators': 500, 'subsample': 0.8}
[ 82/216] F1: 0.6247 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 7, 'n_estimators': 500, 'subsample': 0.9}
[ 83/216] F1: 0.6245 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.8}
[ 84/216] F1: 0.6247 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.9}
[ 85/216] F1: 0.6249 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 10, 'n_estimators': 400, 'subsample': 0.8}
[ 86/216] F1: 0.6264 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 10, 'n_estimators': 400, 'subsample': 0.9}
[ 87/216] F1: 0.6251 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 10, 'n_estimators': 500, 'subsample': 0.8}
[ 88/216] F1: 0.6269 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 10, 'n_estimators': 500, 'subsample': 0.9}
[ 89/216] F1: 0.6249 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 10, 'n_estimators': 600, 'subsample': 0.8}
[ 90/216] F1: 0.6269 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 11, 'min_child_weight': 10, 'n_estimators': 600, 'subsample': 0.9}
[ 91/216] F1: 0.6265 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.8}
[ 92/216] F1: 0.6263 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.9}
[ 93/216] F1: 0.6261 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[ 94/216] F1: 0.6266 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.9}
[ 95/216] F1: 0.6242 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.8}
[ 96/216] F1: 0.6262 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.9}
[ 97/216] F1: 0.6249 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 400, 'subsample': 0.8}
[ 98/216] F1: 0.6259 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 400, 'subsample': 0.9}
[ 99/216] F1: 0.6248 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 500, 'subsample': 0.8}
[100/216] F1: 0.6269 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 500, 'subsample': 0.9}
[101/216] F1: 0.6233 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.8}
[102/216] F1: 0.6270 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.9}
[103/216] F1: 0.6256 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 10, 'n_estimators': 400, 'subsample': 0.8}
[104/216] F1: 0.6275 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 10, 'n_estimators': 400, 'subsample': 0.9}
[105/216] F1: 0.6259 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 10, 'n_estimators': 500, 'subsample': 0.8}
[106/216] F1: 0.6274 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 10, 'n_estimators': 500, 'subsample': 0.9}
[107/216] F1: 0.6249 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 10, 'n_estimators': 600, 'subsample': 0.8}
[108/216] F1: 0.6264 | {'colsample_bytree': 0.6, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 10, 'n_estimators': 600, 'subsample': 0.9}
[109/216] F1: 0.6197 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.8}
[110/216] F1: 0.6216 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.9}
[111/216] F1: 0.6206 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[112/216] F1: 0.6242 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.9}
[113/216] F1: 0.6230 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.8}
[114/216] F1: 0.6246 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.9}
[115/216] F1: 0.6192 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 400, 'subsample': 0.8}
[116/216] F1: 0.6208 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 400, 'subsample': 0.9}
[117/216] F1: 0.6215 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 500, 'subsample': 0.8}
[118/216] F1: 0.6244 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 500, 'subsample': 0.9}
[119/216] F1: 0.6231 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.8}
[120/216] F1: 0.6251 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.9}
[121/216] F1: 0.6189 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 400, 'subsample': 0.8}
[122/216] F1: 0.6190 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 400, 'subsample': 0.9}
[123/216] F1: 0.6212 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 500, 'subsample': 0.8}
[124/216] F1: 0.6216 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 500, 'subsample': 0.9}
[125/216] F1: 0.6220 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 600, 'subsample': 0.8}
[126/216] F1: 0.6250 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 10, 'min_child_weight': 10, 'n_estimators': 600, 'subsample': 0.9}
[127/216] F1: 0.6236 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.8}
[128/216] F1: 0.6240 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 400, 'subsample': 0.9}
[129/216] F1: 0.6257 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}
[130/216] F1: 0.6265 | {'colsample_bytree': 0.7, 'learning_rate': 0.03, 'max_depth': 11, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.9}

,f1_val,colsample_bytree,learning_rate,max_depth,min_child_weight,n_estimators,subsample
rank,,,,,,,
1,0.628453,0.6,0.03,12,5,600,0.8
2,0.628141,0.7,0.03,12,5,600,0.9
3,0.627793,0.7,0.03,11,5,600,0.9
4,0.627731,0.6,0.03,12,10,600,0.9
5,0.627715,0.7,0.03,12,10,600,0.9
...,...,...,...,...,...,...,...
212,0.620298,0.6,0.03,10,10,400,0.9
213,0.619749,0.7,0.03,10,5,400,0.8
214,0.619192,0.7,0.03,10,7,400,0.8
215,0.619019,0.7,0.03,10,10,400,0.9
216,0.618933,0.7,0.03,10,10,400,0.8

### Execução 4 — Refinamento fino ao redor do melhor

A execução 3 consolidou `colsample_bytree=0.6, learning_rate=0.03, max_depth=12, n_estimators=600` como região ótima. Exploração estreita nessa vizinhança revelou que `max_depth=13` com `subsample=0.9` superou `max_depth=12`, sugerindo ganho residual com árvores ligeiramente mais profundas.

In [ ]:
best_params, best_score, df_results = run_grid_search({
    "n_estimators": [600, 700, 800],
    "max_depth": [12, 13],
    "learning_rate": [0.03],
    "min_child_weight": [5, 7],
    "subsample": [0.8, 0.9],
    "colsample_bytree": [0.6],
})

Total de combinações a testar: 24
================================================================================
[ 1/24] F1: 0.6285 *** NOVO MELHOR | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.8}
[ 2/24] F1: 0.6268 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.9}
[ 3/24] F1: 0.6266 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.8}
[ 4/24] F1: 0.6266 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.9}
[ 5/24] F1: 0.6254 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 800, 'subsample': 0.8}
[ 6/24] F1: 0.6267 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 800, 'subsample': 0.9}
[ 7/24] F1: 0.6265 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.8}
[ 8/24] F1: 0.6275 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.9}
[ 9/24] F1: 0.6251 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 700, 'subsample': 0.8}
[10/24] F1: 0.6272 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 700, 'subsample': 0.9}
[11/24] F1: 0.6253 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 800, 'subsample': 0.8}
[12/24] F1: 0.6274 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 7, 'n_estimators': 800, 'subsample': 0.9}
[13/24] F1: 0.6259 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.8}
[14/24] F1: 0.6283 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.9}
[15/24] F1: 0.6258 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.8}
[16/24] F1: 0.6285 *** NOVO MELHOR | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 5, 'n_estimators': 700, 'subsample': 0.9}
[17/24] F1: 0.6245 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 5, 'n_estimators': 800, 'subsample': 0.8}
[18/24] F1: 0.6290 *** NOVO MELHOR | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 5, 'n_estimators': 800, 'subsample': 0.9}
[19/24] F1: 0.6254 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.8}
[20/24] F1: 0.6281 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 7, 'n_estimators': 600, 'subsample': 0.9}
[21/24] F1: 0.6251 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 7, 'n_estimators': 700, 'subsample': 0.8}
[22/24] F1: 0.6266 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 7, 'n_estimators': 700, 'subsample': 0.9}
[23/24] F1: 0.6251 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 7, 'n_estimators': 800, 'subsample': 0.8}
[24/24] F1: 0.6262 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 7, 'n_estimators': 800, 'subsample': 0.9}
================================================================================

Melhores hiperparâmetros: {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 5, 'n_estimators': 800, 'subsample': 0.9}
Melhor F1 (validação): 0.6290

,f1_val,colsample_bytree,learning_rate,max_depth,min_child_weight,n_estimators,subsample
rank,,,,,,,
1,0.629023,0.6,0.03,13,5,800,0.9
2,0.628477,0.6,0.03,13,5,700,0.9
3,0.628453,0.6,0.03,12,5,600,0.8
4,0.628268,0.6,0.03,13,5,600,0.9
5,0.628075,0.6,0.03,13,7,600,0.9
6,0.627508,0.6,0.03,12,7,600,0.9
7,0.627412,0.6,0.03,12,7,800,0.9
8,0.627193,0.6,0.03,12,7,700,0.9
9,0.626777,0.6,0.03,12,5,600,0.9
10,0.626745,0.6,0.03,12,5,800,0.9
11,0.626579,0.6,0.03,12,5,700,0.8
12,0.626574,0.6,0.03,12,5,700,0.9
13,0.626552,0.6,0.03,13,7,700,0.9
14,0.626500,0.6,0.03,12,7,600,0.8
15,0.626182,0.6,0.03,13,7,800,0.9
16,0.625879,0.6,0.03,13,5,600,0.8
17,0.625789,0.6,0.03,13,5,700,0.8
18,0.625439,0.6,0.03,13,7,600,0.8
19,0.625363,0.6,0.03,12,5,800,0.8
20,0.625284,0.6,0.03,12,7,800,0.8
21,0.625121,0.6,0.03,13,7,800,0.8
22,0.625065,0.6,0.03,12,7,700,0.8
23,0.625052,0.6,0.03,13,7,700,0.8
24,0.624540,0.6,0.03,13,5,800,0.8


### Execução 5 — Verificação do teto

A execução 4 confirmou `max_depth=13` como promissor, ainda na borda superior da grade. Testou-se `max_depth=14` e `n_estimators` maiores para verificar se havia ganho adicional. Ambos pioraram o F1, confirmando overfitting e indicando que os parâmetros da execução 4 representam o teto do modelo.

In [6]:
best_params, best_score, df_results = run_grid_search({
    "n_estimators": [800, 1000, 1200],
    "max_depth": [13, 14],
    "learning_rate": [0.03],
    "min_child_weight": [5],
    "subsample": [0.9],
    "colsample_bytree": [0.6],
})

Total de combinações a testar: 6
================================================================================
[1/6] F1: 0.6290 *** NOVO MELHOR | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 5, 'n_estimators': 800, 'subsample': 0.9}
[2/6] F1: 0.6275 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.9}
[3/6] F1: 0.6264 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 5, 'n_estimators': 1200, 'subsample': 0.9}
[4/6] F1: 0.6251 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 14, 'min_child_weight': 5, 'n_estimators': 800, 'subsample': 0.9}
[5/6] F1: 0.6245 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 14, 'min_child_weight': 5, 'n_estimators': 1000, 'subsample': 0.9}
[6/6] F1: 0.6222 | {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 14, 'min_child_weight': 5, 'n_estimators': 1200, 'subsample': 0.9}
================================================================================

Melhores hiperparâmetros: {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 5, 'n_estimators': 800, 'subsample': 0.9}
Melhor F1 (validação): 0.6290

,f1_val,colsample_bytree,learning_rate,max_depth,min_child_weight,n_estimators,subsample
rank,,,,,,,
1,0.629023,0.6,0.03,13,5,800,0.9
2,0.627478,0.6,0.03,13,5,1000,0.9
3,0.626414,0.6,0.03,13,5,1200,0.9
4,0.625116,0.6,0.03,14,5,800,0.9
5,0.624489,0.6,0.03,14,5,1000,0.9
6,0.622188,0.6,0.03,14,5,1200,0.9

## 5. Treinar modelo final no treino completo e avaliar no teste holdout

Quando encontrar os melhores parâmetros, execute esta cell para treinar no treino completo e avaliar no teste.

In [18]:
# best_params = {'colsample_bytree': 0.8, 'learning_rate': 0.1, 'max_depth': 8, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8}   # F1 0.6209
# best_params = {'colsample_bytree': 0.7, 'learning_rate': 0.05, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 500, 'subsample': 0.8} # F1 0.6263
# best_params = {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 12, 'min_child_weight': 5, 'n_estimators': 600, 'subsample': 0.8} # F1 0.6285
best_params = {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 5, 'n_estimators': 800, 'subsample': 0.9} # F1 0.6290

In [7]:
# Treina com os melhores hiperparâmetros no treino COMPLETO
print(f"Treinando modelo final com: {best_params}")
print(f"Treino completo: {X_train_full.shape[0]:,} registros")

final_clf = XGBClassifier(
    **best_params,
    objective="binary:logistic",
    eval_metric="logloss",
    n_jobs=-1,
    random_state=RANDOM_STATE,
)

final_pipe = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", final_clf),
])

final_pipe.fit(X_train_full, y_train_full)
y_test_pred = final_pipe.predict(X_test)

target_names = ["Desligamento (-1)", "Admissão (1)"]

print("\n" + "=" * 80)
print("AVALIAÇÃO NO TESTE HOLDOUT")
print("=" * 80)
print(f"  F1 Score (binary)    : {f1_score(y_test, y_test_pred):.4f}  ← métrica principal")
print(f"  F1 Score (macro)     : {f1_score(y_test, y_test_pred, average='macro'):.4f}")
print(f"  F1 Score (weighted)  : {f1_score(y_test, y_test_pred, average='weighted'):.4f}")
print(f"  Accuracy             : {accuracy_score(y_test, y_test_pred):.4f}")
print(f"  Balanced Accuracy    : {balanced_accuracy_score(y_test, y_test_pred):.4f}")
print(f"  MCC                  : {matthews_corrcoef(y_test, y_test_pred):.4f}")
print("-" * 80)
print("Classification Report:")
print(classification_report(y_test, y_test_pred, target_names=target_names, digits=4))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))

Treinando modelo final com: {'colsample_bytree': 0.6, 'learning_rate': 0.03, 'max_depth': 13, 'min_child_weight': 5, 'n_estimators': 800, 'subsample': 0.9}
Treino completo: 591,069 registros

================================================================================
AVALIAÇÃO NO TESTE HOLDOUT
================================================================================
  F1 Score (binary)    : 0.6263  ← métrica principal
  F1 Score (macro)     : 0.6307
  F1 Score (weighted)  : 0.6308
  Accuracy             : 0.6307
  Balanced Accuracy    : 0.6308
  MCC                  : 0.2615
--------------------------------------------------------------------------------
Classification Report:
                   precision    recall  f1-score   support

Desligamento (-1)     0.6410    0.6292    0.6351     75451
     Admissão (1)     0.6204    0.6323    0.6263     72317

         accuracy                         0.6307    147768
        macro avg     0.6307    0.6308    0.6307    147768
     weighted avg     0.6309    0.6307    0.6308    147768

Confusion Matrix:
[[47477 27974]
 [26591 45726]]

## 6. Copie os melhores parâmetros para o `config.py`

Quando estiver satisfeito com os resultados, copie o `best_params` para o `XGBOOST_PARAM_GRID` do `config.py` (com listas de um só elemento) e rode `python main.py`.

In [ ]:
print("Cole no config.py XGBOOST_PARAM_GRID:")
print()
print("XGBOOST_PARAM_GRID = {")
for k, v in best_params.items():
    print(f'    "{k}": [{repr(v)}],')
print("}")